### ISSUE TITLE
Incorrect cloudflare_warp.mobileconfig

### ISSUE THREAD

**Issue by kartikarora** [kandji-inc/support#14]
The `mobileconfig` file for Clouflare WARP available at https://github.com/kandji-inc/support/blob/main/Configuration%20Profiles/cloudflare_warp.mobileconfig has a missing `</array>` on line 33-34. This leads to a failure in creating a warp custom profile on Kandji.

**Comment by captam3rica** [comment]
will update this profile. thanks for the call out.

**Comment by kartikarora** [comment]
Fixed in ff35e53
