### ISSUE TITLE
CrowdStrike macOS settings file (without kext) for Sequoia (v15) is not working

### ISSUE THREAD

**Issue by jordigg** [kandji-inc/support#33]
Hi there,

I've been testing the new provided configs for deploying CrowdStrike on Sequoia.
The [crowdstrike_settings_macOS15.mobileconfig](https://github.com/kandji-inc/support/blob/main/custom-apps/crowdstrike/crowdstrike_settings_macOS15.mobileconfig) file currently outputs the following error when deployed:

> In the payload (UUID: 9A10BE5D-5E46-4C22-89C9-20597A04B616), the key 'Authorization and Allowed' is not allowed. (NSPOSIXErrorDomain: 22)

The problem is that in a TCC you can't have an `Authorization` and a `Allowed` keys referenced at the same time. These are found inside the `BluetoothAlways` key.

There are two solutions, either remove the whole `BluetoothAlways` key or fix the `Authorization` and `Allowed` issue by using a single one. `Allowed` like in `SystemPolicyAllFiles` should work.
I would prefer for the [BluetoothAlways](https://github.com/kandji-inc/support/blob/d05964df4881a937804498ac9399fd42f95b01f8/custom-apps/crowdstrike/crowdstrike_settings_macOS15.mobileconfig#L60-L90) part to be removed since CrowdStrike doesn't seem to require this. At least I haven't been able to find any reference in the documentation.

https://github.com/kandji-inc/support/blob/d05964df4881a937804498ac9399fd42f95b01f8/custom-apps/crowdstrike/crowdstrike_settings_macOS15.mobileconfig#L60-L90

I have tested the mobileconfig without the `BluetoothAlways` key and works fine so far on our test environment.

I was going to send a PR for this, but didn't if you knew why `BluetoothAlways` was there. For example in the [crowdstrike_settings_with_kext_macOS15.mobileconfig](https://github.com/kandji-inc/support/blob/main/custom-apps/crowdstrike/crowdstrike_settings_with_kext_macOS15.mobileconfig) it's not set and the profile works fine without changes.

Here a [Gist](https://gist.github.com/jordigg/7ba4aca98d6dde2e2c851b03753f2ade) with a working version.

**Comment by nickmcdon** [comment]
Resolved
