### ISSUE TITLE
InstallHomebrew.sh fails if Xcode CLI tools are not installed

### ISSUE THREAD

**Issue by seb-plutoflume** [kandji-inc/support#9]
I tried the InstallHomebrew.sh from this repo as describe in the [Deploying Homebrew as a Custom Script](https://support.kandji.io/homebrew) support article. It fails if Apple's Command Line Tools for Xcode are not installed.

I understand this is a Homebrew requirement, but was expecting that the script would handle that scenario. Meaning the script would be more resilient and could be made available as a Self Service item.

**Comment by captam3rica** [comment]
Hi @seb-plutoflume, thank you for the feedback. an update to account for this has been added to the homebrew installer script.
